package com.zhidisoft.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrmBusinessExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public CrmBusinessExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andOriginIsNull() {
			addCriterion("ORIGIN is null");
			return (Criteria) this;
		}

		public Criteria andOriginIsNotNull() {
			addCriterion("ORIGIN is not null");
			return (Criteria) this;
		}

		public Criteria andOriginEqualTo(String value) {
			addCriterion("ORIGIN =", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginNotEqualTo(String value) {
			addCriterion("ORIGIN <>", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginGreaterThan(String value) {
			addCriterion("ORIGIN >", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginGreaterThanOrEqualTo(String value) {
			addCriterion("ORIGIN >=", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginLessThan(String value) {
			addCriterion("ORIGIN <", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginLessThanOrEqualTo(String value) {
			addCriterion("ORIGIN <=", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginLike(String value) {
			addCriterion("ORIGIN like", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginNotLike(String value) {
			addCriterion("ORIGIN not like", value, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginIn(List<String> values) {
			addCriterion("ORIGIN in", values, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginNotIn(List<String> values) {
			addCriterion("ORIGIN not in", values, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginBetween(String value1, String value2) {
			addCriterion("ORIGIN between", value1, value2, "origin");
			return (Criteria) this;
		}

		public Criteria andOriginNotBetween(String value1, String value2) {
			addCriterion("ORIGIN not between", value1, value2, "origin");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("TYPE is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("TYPE =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("TYPE <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("TYPE >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("TYPE >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("TYPE <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("TYPE <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("TYPE like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("TYPE not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("TYPE in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("TYPE not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("TYPE between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("TYPE not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceIsNull() {
			addCriterion("ESTIMATEPRICE is null");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceIsNotNull() {
			addCriterion("ESTIMATEPRICE is not null");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceEqualTo(Long value) {
			addCriterion("ESTIMATEPRICE =", value, "estimateprice");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceNotEqualTo(Long value) {
			addCriterion("ESTIMATEPRICE <>", value, "estimateprice");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceGreaterThan(Long value) {
			addCriterion("ESTIMATEPRICE >", value, "estimateprice");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceGreaterThanOrEqualTo(Long value) {
			addCriterion("ESTIMATEPRICE >=", value, "estimateprice");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceLessThan(Long value) {
			addCriterion("ESTIMATEPRICE <", value, "estimateprice");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceLessThanOrEqualTo(Long value) {
			addCriterion("ESTIMATEPRICE <=", value, "estimateprice");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceIn(List<Long> values) {
			addCriterion("ESTIMATEPRICE in", values, "estimateprice");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceNotIn(List<Long> values) {
			addCriterion("ESTIMATEPRICE not in", values, "estimateprice");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceBetween(Long value1, Long value2) {
			addCriterion("ESTIMATEPRICE between", value1, value2, "estimateprice");
			return (Criteria) this;
		}

		public Criteria andEstimatepriceNotBetween(Long value1, Long value2) {
			addCriterion("ESTIMATEPRICE not between", value1, value2, "estimateprice");
			return (Criteria) this;
		}

		public Criteria andCustomeridIsNull() {
			addCriterion("CUSTOMERID is null");
			return (Criteria) this;
		}

		public Criteria andCustomeridIsNotNull() {
			addCriterion("CUSTOMERID is not null");
			return (Criteria) this;
		}

		public Criteria andCustomeridEqualTo(Long value) {
			addCriterion("CUSTOMERID =", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotEqualTo(Long value) {
			addCriterion("CUSTOMERID <>", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridGreaterThan(Long value) {
			addCriterion("CUSTOMERID >", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridGreaterThanOrEqualTo(Long value) {
			addCriterion("CUSTOMERID >=", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridLessThan(Long value) {
			addCriterion("CUSTOMERID <", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridLessThanOrEqualTo(Long value) {
			addCriterion("CUSTOMERID <=", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridIn(List<Long> values) {
			addCriterion("CUSTOMERID in", values, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotIn(List<Long> values) {
			addCriterion("CUSTOMERID not in", values, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridBetween(Long value1, Long value2) {
			addCriterion("CUSTOMERID between", value1, value2, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotBetween(Long value1, Long value2) {
			addCriterion("CUSTOMERID not between", value1, value2, "customerid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridIsNull() {
			addCriterion("CREATORUSERID is null");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridIsNotNull() {
			addCriterion("CREATORUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridEqualTo(String value) {
			addCriterion("CREATORUSERID =", value, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridNotEqualTo(String value) {
			addCriterion("CREATORUSERID <>", value, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridGreaterThan(String value) {
			addCriterion("CREATORUSERID >", value, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridGreaterThanOrEqualTo(String value) {
			addCriterion("CREATORUSERID >=", value, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridLessThan(String value) {
			addCriterion("CREATORUSERID <", value, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridLessThanOrEqualTo(String value) {
			addCriterion("CREATORUSERID <=", value, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridLike(String value) {
			addCriterion("CREATORUSERID like", value, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridNotLike(String value) {
			addCriterion("CREATORUSERID not like", value, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridIn(List<String> values) {
			addCriterion("CREATORUSERID in", values, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridNotIn(List<String> values) {
			addCriterion("CREATORUSERID not in", values, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridBetween(String value1, String value2) {
			addCriterion("CREATORUSERID between", value1, value2, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andCreatoruseridNotBetween(String value1, String value2) {
			addCriterion("CREATORUSERID not between", value1, value2, "creatoruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridIsNull() {
			addCriterion("OWNERUSERID is null");
			return (Criteria) this;
		}

		public Criteria andOwneruseridIsNotNull() {
			addCriterion("OWNERUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andOwneruseridEqualTo(String value) {
			addCriterion("OWNERUSERID =", value, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridNotEqualTo(String value) {
			addCriterion("OWNERUSERID <>", value, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridGreaterThan(String value) {
			addCriterion("OWNERUSERID >", value, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridGreaterThanOrEqualTo(String value) {
			addCriterion("OWNERUSERID >=", value, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridLessThan(String value) {
			addCriterion("OWNERUSERID <", value, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridLessThanOrEqualTo(String value) {
			addCriterion("OWNERUSERID <=", value, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridLike(String value) {
			addCriterion("OWNERUSERID like", value, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridNotLike(String value) {
			addCriterion("OWNERUSERID not like", value, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridIn(List<String> values) {
			addCriterion("OWNERUSERID in", values, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridNotIn(List<String> values) {
			addCriterion("OWNERUSERID not in", values, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridBetween(String value1, String value2) {
			addCriterion("OWNERUSERID between", value1, value2, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andOwneruseridNotBetween(String value1, String value2) {
			addCriterion("OWNERUSERID not between", value1, value2, "owneruserid");
			return (Criteria) this;
		}

		public Criteria andGainrateIsNull() {
			addCriterion("GAINRATE is null");
			return (Criteria) this;
		}

		public Criteria andGainrateIsNotNull() {
			addCriterion("GAINRATE is not null");
			return (Criteria) this;
		}

		public Criteria andGainrateEqualTo(BigDecimal value) {
			addCriterion("GAINRATE =", value, "gainrate");
			return (Criteria) this;
		}

		public Criteria andGainrateNotEqualTo(BigDecimal value) {
			addCriterion("GAINRATE <>", value, "gainrate");
			return (Criteria) this;
		}

		public Criteria andGainrateGreaterThan(BigDecimal value) {
			addCriterion("GAINRATE >", value, "gainrate");
			return (Criteria) this;
		}

		public Criteria andGainrateGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("GAINRATE >=", value, "gainrate");
			return (Criteria) this;
		}

		public Criteria andGainrateLessThan(BigDecimal value) {
			addCriterion("GAINRATE <", value, "gainrate");
			return (Criteria) this;
		}

		public Criteria andGainrateLessThanOrEqualTo(BigDecimal value) {
			addCriterion("GAINRATE <=", value, "gainrate");
			return (Criteria) this;
		}

		public Criteria andGainrateIn(List<BigDecimal> values) {
			addCriterion("GAINRATE in", values, "gainrate");
			return (Criteria) this;
		}

		public Criteria andGainrateNotIn(List<BigDecimal> values) {
			addCriterion("GAINRATE not in", values, "gainrate");
			return (Criteria) this;
		}

		public Criteria andGainrateBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("GAINRATE between", value1, value2, "gainrate");
			return (Criteria) this;
		}

		public Criteria andGainrateNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("GAINRATE not between", value1, value2, "gainrate");
			return (Criteria) this;
		}

		public Criteria andTotalamountIsNull() {
			addCriterion("TOTALAMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andTotalamountIsNotNull() {
			addCriterion("TOTALAMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andTotalamountEqualTo(Long value) {
			addCriterion("TOTALAMOUNT =", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountNotEqualTo(Long value) {
			addCriterion("TOTALAMOUNT <>", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountGreaterThan(Long value) {
			addCriterion("TOTALAMOUNT >", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountGreaterThanOrEqualTo(Long value) {
			addCriterion("TOTALAMOUNT >=", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountLessThan(Long value) {
			addCriterion("TOTALAMOUNT <", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountLessThanOrEqualTo(Long value) {
			addCriterion("TOTALAMOUNT <=", value, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountIn(List<Long> values) {
			addCriterion("TOTALAMOUNT in", values, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountNotIn(List<Long> values) {
			addCriterion("TOTALAMOUNT not in", values, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountBetween(Long value1, Long value2) {
			addCriterion("TOTALAMOUNT between", value1, value2, "totalamount");
			return (Criteria) this;
		}

		public Criteria andTotalamountNotBetween(Long value1, Long value2) {
			addCriterion("TOTALAMOUNT not between", value1, value2, "totalamount");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalIsNull() {
			addCriterion("SUBTOTALVAL is null");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalIsNotNull() {
			addCriterion("SUBTOTALVAL is not null");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalEqualTo(BigDecimal value) {
			addCriterion("SUBTOTALVAL =", value, "subtotalval");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalNotEqualTo(BigDecimal value) {
			addCriterion("SUBTOTALVAL <>", value, "subtotalval");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalGreaterThan(BigDecimal value) {
			addCriterion("SUBTOTALVAL >", value, "subtotalval");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("SUBTOTALVAL >=", value, "subtotalval");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalLessThan(BigDecimal value) {
			addCriterion("SUBTOTALVAL <", value, "subtotalval");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalLessThanOrEqualTo(BigDecimal value) {
			addCriterion("SUBTOTALVAL <=", value, "subtotalval");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalIn(List<BigDecimal> values) {
			addCriterion("SUBTOTALVAL in", values, "subtotalval");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalNotIn(List<BigDecimal> values) {
			addCriterion("SUBTOTALVAL not in", values, "subtotalval");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("SUBTOTALVAL between", value1, value2, "subtotalval");
			return (Criteria) this;
		}

		public Criteria andSubtotalvalNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("SUBTOTALVAL not between", value1, value2, "subtotalval");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceIsNull() {
			addCriterion("DISCOUNTPRICE is null");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceIsNotNull() {
			addCriterion("DISCOUNTPRICE is not null");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceEqualTo(Long value) {
			addCriterion("DISCOUNTPRICE =", value, "discountprice");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceNotEqualTo(Long value) {
			addCriterion("DISCOUNTPRICE <>", value, "discountprice");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceGreaterThan(Long value) {
			addCriterion("DISCOUNTPRICE >", value, "discountprice");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceGreaterThanOrEqualTo(Long value) {
			addCriterion("DISCOUNTPRICE >=", value, "discountprice");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceLessThan(Long value) {
			addCriterion("DISCOUNTPRICE <", value, "discountprice");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceLessThanOrEqualTo(Long value) {
			addCriterion("DISCOUNTPRICE <=", value, "discountprice");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceIn(List<Long> values) {
			addCriterion("DISCOUNTPRICE in", values, "discountprice");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceNotIn(List<Long> values) {
			addCriterion("DISCOUNTPRICE not in", values, "discountprice");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceBetween(Long value1, Long value2) {
			addCriterion("DISCOUNTPRICE between", value1, value2, "discountprice");
			return (Criteria) this;
		}

		public Criteria andDiscountpriceNotBetween(Long value1, Long value2) {
			addCriterion("DISCOUNTPRICE not between", value1, value2, "discountprice");
			return (Criteria) this;
		}

		public Criteria andSalespriceIsNull() {
			addCriterion("SALESPRICE is null");
			return (Criteria) this;
		}

		public Criteria andSalespriceIsNotNull() {
			addCriterion("SALESPRICE is not null");
			return (Criteria) this;
		}

		public Criteria andSalespriceEqualTo(Long value) {
			addCriterion("SALESPRICE =", value, "salesprice");
			return (Criteria) this;
		}

		public Criteria andSalespriceNotEqualTo(Long value) {
			addCriterion("SALESPRICE <>", value, "salesprice");
			return (Criteria) this;
		}

		public Criteria andSalespriceGreaterThan(Long value) {
			addCriterion("SALESPRICE >", value, "salesprice");
			return (Criteria) this;
		}

		public Criteria andSalespriceGreaterThanOrEqualTo(Long value) {
			addCriterion("SALESPRICE >=", value, "salesprice");
			return (Criteria) this;
		}

		public Criteria andSalespriceLessThan(Long value) {
			addCriterion("SALESPRICE <", value, "salesprice");
			return (Criteria) this;
		}

		public Criteria andSalespriceLessThanOrEqualTo(Long value) {
			addCriterion("SALESPRICE <=", value, "salesprice");
			return (Criteria) this;
		}

		public Criteria andSalespriceIn(List<Long> values) {
			addCriterion("SALESPRICE in", values, "salesprice");
			return (Criteria) this;
		}

		public Criteria andSalespriceNotIn(List<Long> values) {
			addCriterion("SALESPRICE not in", values, "salesprice");
			return (Criteria) this;
		}

		public Criteria andSalespriceBetween(Long value1, Long value2) {
			addCriterion("SALESPRICE between", value1, value2, "salesprice");
			return (Criteria) this;
		}

		public Criteria andSalespriceNotBetween(Long value1, Long value2) {
			addCriterion("SALESPRICE not between", value1, value2, "salesprice");
			return (Criteria) this;
		}

		public Criteria andDuedateIsNull() {
			addCriterion("DUEDATE is null");
			return (Criteria) this;
		}

		public Criteria andDuedateIsNotNull() {
			addCriterion("DUEDATE is not null");
			return (Criteria) this;
		}

		public Criteria andDuedateEqualTo(Date value) {
			addCriterion("DUEDATE =", value, "duedate");
			return (Criteria) this;
		}

		public Criteria andDuedateNotEqualTo(Date value) {
			addCriterion("DUEDATE <>", value, "duedate");
			return (Criteria) this;
		}

		public Criteria andDuedateGreaterThan(Date value) {
			addCriterion("DUEDATE >", value, "duedate");
			return (Criteria) this;
		}

		public Criteria andDuedateGreaterThanOrEqualTo(Date value) {
			addCriterion("DUEDATE >=", value, "duedate");
			return (Criteria) this;
		}

		public Criteria andDuedateLessThan(Date value) {
			addCriterion("DUEDATE <", value, "duedate");
			return (Criteria) this;
		}

		public Criteria andDuedateLessThanOrEqualTo(Date value) {
			addCriterion("DUEDATE <=", value, "duedate");
			return (Criteria) this;
		}

		public Criteria andDuedateIn(List<Date> values) {
			addCriterion("DUEDATE in", values, "duedate");
			return (Criteria) this;
		}

		public Criteria andDuedateNotIn(List<Date> values) {
			addCriterion("DUEDATE not in", values, "duedate");
			return (Criteria) this;
		}

		public Criteria andDuedateBetween(Date value1, Date value2) {
			addCriterion("DUEDATE between", value1, value2, "duedate");
			return (Criteria) this;
		}

		public Criteria andDuedateNotBetween(Date value1, Date value2) {
			addCriterion("DUEDATE not between", value1, value2, "duedate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIsNull() {
			addCriterion("GMT_CREATE is null");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIsNotNull() {
			addCriterion("GMT_CREATE is not null");
			return (Criteria) this;
		}

		public Criteria andGmtCreateEqualTo(Date value) {
			addCriterion("GMT_CREATE =", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotEqualTo(Date value) {
			addCriterion("GMT_CREATE <>", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateGreaterThan(Date value) {
			addCriterion("GMT_CREATE >", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
			addCriterion("GMT_CREATE >=", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateLessThan(Date value) {
			addCriterion("GMT_CREATE <", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
			addCriterion("GMT_CREATE <=", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIn(List<Date> values) {
			addCriterion("GMT_CREATE in", values, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotIn(List<Date> values) {
			addCriterion("GMT_CREATE not in", values, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateBetween(Date value1, Date value2) {
			addCriterion("GMT_CREATE between", value1, value2, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
			addCriterion("GMT_CREATE not between", value1, value2, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedIsNull() {
			addCriterion("GMT_MODIFIED is null");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedIsNotNull() {
			addCriterion("GMT_MODIFIED is not null");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedEqualTo(Date value) {
			addCriterion("GMT_MODIFIED =", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedNotEqualTo(Date value) {
			addCriterion("GMT_MODIFIED <>", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedGreaterThan(Date value) {
			addCriterion("GMT_MODIFIED >", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
			addCriterion("GMT_MODIFIED >=", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedLessThan(Date value) {
			addCriterion("GMT_MODIFIED <", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
			addCriterion("GMT_MODIFIED <=", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedIn(List<Date> values) {
			addCriterion("GMT_MODIFIED in", values, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedNotIn(List<Date> values) {
			addCriterion("GMT_MODIFIED not in", values, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedBetween(Date value1, Date value2) {
			addCriterion("GMT_MODIFIED between", value1, value2, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
			addCriterion("GMT_MODIFIED not between", value1, value2, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridIsNull() {
			addCriterion("UPDATEUSERID is null");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridIsNotNull() {
			addCriterion("UPDATEUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridEqualTo(String value) {
			addCriterion("UPDATEUSERID =", value, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridNotEqualTo(String value) {
			addCriterion("UPDATEUSERID <>", value, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridGreaterThan(String value) {
			addCriterion("UPDATEUSERID >", value, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATEUSERID >=", value, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridLessThan(String value) {
			addCriterion("UPDATEUSERID <", value, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridLessThanOrEqualTo(String value) {
			addCriterion("UPDATEUSERID <=", value, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridLike(String value) {
			addCriterion("UPDATEUSERID like", value, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridNotLike(String value) {
			addCriterion("UPDATEUSERID not like", value, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridIn(List<String> values) {
			addCriterion("UPDATEUSERID in", values, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridNotIn(List<String> values) {
			addCriterion("UPDATEUSERID not in", values, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridBetween(String value1, String value2) {
			addCriterion("UPDATEUSERID between", value1, value2, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andUpdateuseridNotBetween(String value1, String value2) {
			addCriterion("UPDATEUSERID not between", value1, value2, "updateuserid");
			return (Criteria) this;
		}

		public Criteria andStatusidIsNull() {
			addCriterion("STATUSID is null");
			return (Criteria) this;
		}

		public Criteria andStatusidIsNotNull() {
			addCriterion("STATUSID is not null");
			return (Criteria) this;
		}

		public Criteria andStatusidEqualTo(String value) {
			addCriterion("STATUSID =", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidNotEqualTo(String value) {
			addCriterion("STATUSID <>", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidGreaterThan(String value) {
			addCriterion("STATUSID >", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidGreaterThanOrEqualTo(String value) {
			addCriterion("STATUSID >=", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidLessThan(String value) {
			addCriterion("STATUSID <", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidLessThanOrEqualTo(String value) {
			addCriterion("STATUSID <=", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidLike(String value) {
			addCriterion("STATUSID like", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidNotLike(String value) {
			addCriterion("STATUSID not like", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidIn(List<String> values) {
			addCriterion("STATUSID in", values, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidNotIn(List<String> values) {
			addCriterion("STATUSID not in", values, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidBetween(String value1, String value2) {
			addCriterion("STATUSID between", value1, value2, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidNotBetween(String value1, String value2) {
			addCriterion("STATUSID not between", value1, value2, "statusid");
			return (Criteria) this;
		}

		public Criteria andTotalpriceIsNull() {
			addCriterion("TOTALPRICE is null");
			return (Criteria) this;
		}

		public Criteria andTotalpriceIsNotNull() {
			addCriterion("TOTALPRICE is not null");
			return (Criteria) this;
		}

		public Criteria andTotalpriceEqualTo(Long value) {
			addCriterion("TOTALPRICE =", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceNotEqualTo(Long value) {
			addCriterion("TOTALPRICE <>", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceGreaterThan(Long value) {
			addCriterion("TOTALPRICE >", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceGreaterThanOrEqualTo(Long value) {
			addCriterion("TOTALPRICE >=", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceLessThan(Long value) {
			addCriterion("TOTALPRICE <", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceLessThanOrEqualTo(Long value) {
			addCriterion("TOTALPRICE <=", value, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceIn(List<Long> values) {
			addCriterion("TOTALPRICE in", values, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceNotIn(List<Long> values) {
			addCriterion("TOTALPRICE not in", values, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceBetween(Long value1, Long value2) {
			addCriterion("TOTALPRICE between", value1, value2, "totalprice");
			return (Criteria) this;
		}

		public Criteria andTotalpriceNotBetween(Long value1, Long value2) {
			addCriterion("TOTALPRICE not between", value1, value2, "totalprice");
			return (Criteria) this;
		}

		public Criteria andNextstepIsNull() {
			addCriterion("NEXTSTEP is null");
			return (Criteria) this;
		}

		public Criteria andNextstepIsNotNull() {
			addCriterion("NEXTSTEP is not null");
			return (Criteria) this;
		}

		public Criteria andNextstepEqualTo(String value) {
			addCriterion("NEXTSTEP =", value, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextstepNotEqualTo(String value) {
			addCriterion("NEXTSTEP <>", value, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextstepGreaterThan(String value) {
			addCriterion("NEXTSTEP >", value, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextstepGreaterThanOrEqualTo(String value) {
			addCriterion("NEXTSTEP >=", value, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextstepLessThan(String value) {
			addCriterion("NEXTSTEP <", value, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextstepLessThanOrEqualTo(String value) {
			addCriterion("NEXTSTEP <=", value, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextstepLike(String value) {
			addCriterion("NEXTSTEP like", value, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextstepNotLike(String value) {
			addCriterion("NEXTSTEP not like", value, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextstepIn(List<String> values) {
			addCriterion("NEXTSTEP in", values, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextstepNotIn(List<String> values) {
			addCriterion("NEXTSTEP not in", values, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextstepBetween(String value1, String value2) {
			addCriterion("NEXTSTEP between", value1, value2, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextstepNotBetween(String value1, String value2) {
			addCriterion("NEXTSTEP not between", value1, value2, "nextstep");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeIsNull() {
			addCriterion("NEXTSTEPTIME is null");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeIsNotNull() {
			addCriterion("NEXTSTEPTIME is not null");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeEqualTo(String value) {
			addCriterion("NEXTSTEPTIME =", value, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeNotEqualTo(String value) {
			addCriterion("NEXTSTEPTIME <>", value, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeGreaterThan(String value) {
			addCriterion("NEXTSTEPTIME >", value, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeGreaterThanOrEqualTo(String value) {
			addCriterion("NEXTSTEPTIME >=", value, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeLessThan(String value) {
			addCriterion("NEXTSTEPTIME <", value, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeLessThanOrEqualTo(String value) {
			addCriterion("NEXTSTEPTIME <=", value, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeLike(String value) {
			addCriterion("NEXTSTEPTIME like", value, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeNotLike(String value) {
			addCriterion("NEXTSTEPTIME not like", value, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeIn(List<String> values) {
			addCriterion("NEXTSTEPTIME in", values, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeNotIn(List<String> values) {
			addCriterion("NEXTSTEPTIME not in", values, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeBetween(String value1, String value2) {
			addCriterion("NEXTSTEPTIME between", value1, value2, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andNextsteptimeNotBetween(String value1, String value2) {
			addCriterion("NEXTSTEPTIME not between", value1, value2, "nextsteptime");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNull() {
			addCriterion("ISDELETED is null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNotNull() {
			addCriterion("ISDELETED is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedEqualTo(Long value) {
			addCriterion("ISDELETED =", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotEqualTo(Long value) {
			addCriterion("ISDELETED <>", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThan(Long value) {
			addCriterion("ISDELETED >", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThanOrEqualTo(Long value) {
			addCriterion("ISDELETED >=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThan(Long value) {
			addCriterion("ISDELETED <", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThanOrEqualTo(Long value) {
			addCriterion("ISDELETED <=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIn(List<Long> values) {
			addCriterion("ISDELETED in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotIn(List<Long> values) {
			addCriterion("ISDELETED not in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedBetween(Long value1, Long value2) {
			addCriterion("ISDELETED between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotBetween(Long value1, Long value2) {
			addCriterion("ISDELETED not between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridIsNull() {
			addCriterion("DELETEUSERID is null");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridIsNotNull() {
			addCriterion("DELETEUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridEqualTo(String value) {
			addCriterion("DELETEUSERID =", value, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridNotEqualTo(String value) {
			addCriterion("DELETEUSERID <>", value, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridGreaterThan(String value) {
			addCriterion("DELETEUSERID >", value, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridGreaterThanOrEqualTo(String value) {
			addCriterion("DELETEUSERID >=", value, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridLessThan(String value) {
			addCriterion("DELETEUSERID <", value, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridLessThanOrEqualTo(String value) {
			addCriterion("DELETEUSERID <=", value, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridLike(String value) {
			addCriterion("DELETEUSERID like", value, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridNotLike(String value) {
			addCriterion("DELETEUSERID not like", value, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridIn(List<String> values) {
			addCriterion("DELETEUSERID in", values, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridNotIn(List<String> values) {
			addCriterion("DELETEUSERID not in", values, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridBetween(String value1, String value2) {
			addCriterion("DELETEUSERID between", value1, value2, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeleteuseridNotBetween(String value1, String value2) {
			addCriterion("DELETEUSERID not between", value1, value2, "deleteuserid");
			return (Criteria) this;
		}

		public Criteria andDeletetimeIsNull() {
			addCriterion("DELETETIME is null");
			return (Criteria) this;
		}

		public Criteria andDeletetimeIsNotNull() {
			addCriterion("DELETETIME is not null");
			return (Criteria) this;
		}

		public Criteria andDeletetimeEqualTo(Date value) {
			addCriterion("DELETETIME =", value, "deletetime");
			return (Criteria) this;
		}

		public Criteria andDeletetimeNotEqualTo(Date value) {
			addCriterion("DELETETIME <>", value, "deletetime");
			return (Criteria) this;
		}

		public Criteria andDeletetimeGreaterThan(Date value) {
			addCriterion("DELETETIME >", value, "deletetime");
			return (Criteria) this;
		}

		public Criteria andDeletetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("DELETETIME >=", value, "deletetime");
			return (Criteria) this;
		}

		public Criteria andDeletetimeLessThan(Date value) {
			addCriterion("DELETETIME <", value, "deletetime");
			return (Criteria) this;
		}

		public Criteria andDeletetimeLessThanOrEqualTo(Date value) {
			addCriterion("DELETETIME <=", value, "deletetime");
			return (Criteria) this;
		}

		public Criteria andDeletetimeIn(List<Date> values) {
			addCriterion("DELETETIME in", values, "deletetime");
			return (Criteria) this;
		}

		public Criteria andDeletetimeNotIn(List<Date> values) {
			addCriterion("DELETETIME not in", values, "deletetime");
			return (Criteria) this;
		}

		public Criteria andDeletetimeBetween(Date value1, Date value2) {
			addCriterion("DELETETIME between", value1, value2, "deletetime");
			return (Criteria) this;
		}

		public Criteria andDeletetimeNotBetween(Date value1, Date value2) {
			addCriterion("DELETETIME not between", value1, value2, "deletetime");
			return (Criteria) this;
		}

		public Criteria andContactsidIsNull() {
			addCriterion("CONTACTSID is null");
			return (Criteria) this;
		}

		public Criteria andContactsidIsNotNull() {
			addCriterion("CONTACTSID is not null");
			return (Criteria) this;
		}

		public Criteria andContactsidEqualTo(Long value) {
			addCriterion("CONTACTSID =", value, "contactsid");
			return (Criteria) this;
		}

		public Criteria andContactsidNotEqualTo(Long value) {
			addCriterion("CONTACTSID <>", value, "contactsid");
			return (Criteria) this;
		}

		public Criteria andContactsidGreaterThan(Long value) {
			addCriterion("CONTACTSID >", value, "contactsid");
			return (Criteria) this;
		}

		public Criteria andContactsidGreaterThanOrEqualTo(Long value) {
			addCriterion("CONTACTSID >=", value, "contactsid");
			return (Criteria) this;
		}

		public Criteria andContactsidLessThan(Long value) {
			addCriterion("CONTACTSID <", value, "contactsid");
			return (Criteria) this;
		}

		public Criteria andContactsidLessThanOrEqualTo(Long value) {
			addCriterion("CONTACTSID <=", value, "contactsid");
			return (Criteria) this;
		}

		public Criteria andContactsidIn(List<Long> values) {
			addCriterion("CONTACTSID in", values, "contactsid");
			return (Criteria) this;
		}

		public Criteria andContactsidNotIn(List<Long> values) {
			addCriterion("CONTACTSID not in", values, "contactsid");
			return (Criteria) this;
		}

		public Criteria andContactsidBetween(Long value1, Long value2) {
			addCriterion("CONTACTSID between", value1, value2, "contactsid");
			return (Criteria) this;
		}

		public Criteria andContactsidNotBetween(Long value1, Long value2) {
			addCriterion("CONTACTSID not between", value1, value2, "contactsid");
			return (Criteria) this;
		}

		public Criteria andContactaddressIsNull() {
			addCriterion("CONTACTADDRESS is null");
			return (Criteria) this;
		}

		public Criteria andContactaddressIsNotNull() {
			addCriterion("CONTACTADDRESS is not null");
			return (Criteria) this;
		}

		public Criteria andContactaddressEqualTo(String value) {
			addCriterion("CONTACTADDRESS =", value, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andContactaddressNotEqualTo(String value) {
			addCriterion("CONTACTADDRESS <>", value, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andContactaddressGreaterThan(String value) {
			addCriterion("CONTACTADDRESS >", value, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andContactaddressGreaterThanOrEqualTo(String value) {
			addCriterion("CONTACTADDRESS >=", value, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andContactaddressLessThan(String value) {
			addCriterion("CONTACTADDRESS <", value, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andContactaddressLessThanOrEqualTo(String value) {
			addCriterion("CONTACTADDRESS <=", value, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andContactaddressLike(String value) {
			addCriterion("CONTACTADDRESS like", value, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andContactaddressNotLike(String value) {
			addCriterion("CONTACTADDRESS not like", value, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andContactaddressIn(List<String> values) {
			addCriterion("CONTACTADDRESS in", values, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andContactaddressNotIn(List<String> values) {
			addCriterion("CONTACTADDRESS not in", values, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andContactaddressBetween(String value1, String value2) {
			addCriterion("CONTACTADDRESS between", value1, value2, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andContactaddressNotBetween(String value1, String value2) {
			addCriterion("CONTACTADDRESS not between", value1, value2, "contactaddress");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("DESCRIPTION is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("DESCRIPTION is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("DESCRIPTION =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("DESCRIPTION <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("DESCRIPTION >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("DESCRIPTION <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("DESCRIPTION like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("DESCRIPTION not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("DESCRIPTION in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("DESCRIPTION not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("DESCRIPTION between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("DESCRIPTION not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andIsDelIsNull() {
			addCriterion("IS_DEL is null");
			return (Criteria) this;
		}

		public Criteria andIsDelIsNotNull() {
			addCriterion("IS_DEL is not null");
			return (Criteria) this;
		}

		public Criteria andIsDelEqualTo(String value) {
			addCriterion("IS_DEL =", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelNotEqualTo(String value) {
			addCriterion("IS_DEL <>", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelGreaterThan(String value) {
			addCriterion("IS_DEL >", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelGreaterThanOrEqualTo(String value) {
			addCriterion("IS_DEL >=", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelLessThan(String value) {
			addCriterion("IS_DEL <", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelLessThanOrEqualTo(String value) {
			addCriterion("IS_DEL <=", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelLike(String value) {
			addCriterion("IS_DEL like", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelNotLike(String value) {
			addCriterion("IS_DEL not like", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelIn(List<String> values) {
			addCriterion("IS_DEL in", values, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelNotIn(List<String> values) {
			addCriterion("IS_DEL not in", values, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelBetween(String value1, String value2) {
			addCriterion("IS_DEL between", value1, value2, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelNotBetween(String value1, String value2) {
			addCriterion("IS_DEL not between", value1, value2, "isDel");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table CRM_BUSINESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CRM_BUSINESS
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 15 09:59:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}