package com.zhidisoft.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CrmBusiness {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.ID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.NAME
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.ORIGIN
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String origin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.TYPE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.ESTIMATEPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Long estimateprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.CUSTOMERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Long customerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.CREATORUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String creatoruserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.OWNERUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String owneruserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.GAINRATE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private BigDecimal gainrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.TOTALAMOUNT
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Long totalamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.SUBTOTALVAL
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private BigDecimal subtotalval;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.DISCOUNTPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Long discountprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.SALESPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Long salesprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.DUEDATE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Date duedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.GMT_CREATE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Date gmtCreate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.GMT_MODIFIED
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Date gmtModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.UPDATEUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String updateuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.STATUSID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String statusid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.TOTALPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Long totalprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.NEXTSTEP
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String nextstep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.NEXTSTEPTIME
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String nextsteptime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.ISDELETED
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Long isdeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.DELETEUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String deleteuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.DELETETIME
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Date deletetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.CONTACTSID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private Long contactsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.CONTACTADDRESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String contactaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.DESCRIPTION
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRM_BUSINESS.IS_DEL
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	private String isDel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.ID
	 * @return  the value of CRM_BUSINESS.ID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.ID
	 * @param id  the value for CRM_BUSINESS.ID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.NAME
	 * @return  the value of CRM_BUSINESS.NAME
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.NAME
	 * @param name  the value for CRM_BUSINESS.NAME
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.ORIGIN
	 * @return  the value of CRM_BUSINESS.ORIGIN
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getOrigin() {
		return origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.ORIGIN
	 * @param origin  the value for CRM_BUSINESS.ORIGIN
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setOrigin(String origin) {
		this.origin = origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.TYPE
	 * @return  the value of CRM_BUSINESS.TYPE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.TYPE
	 * @param type  the value for CRM_BUSINESS.TYPE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.ESTIMATEPRICE
	 * @return  the value of CRM_BUSINESS.ESTIMATEPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Long getEstimateprice() {
		return estimateprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.ESTIMATEPRICE
	 * @param estimateprice  the value for CRM_BUSINESS.ESTIMATEPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setEstimateprice(Long estimateprice) {
		this.estimateprice = estimateprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.CUSTOMERID
	 * @return  the value of CRM_BUSINESS.CUSTOMERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Long getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.CUSTOMERID
	 * @param customerid  the value for CRM_BUSINESS.CUSTOMERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setCustomerid(Long customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.CREATORUSERID
	 * @return  the value of CRM_BUSINESS.CREATORUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getCreatoruserid() {
		return creatoruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.CREATORUSERID
	 * @param creatoruserid  the value for CRM_BUSINESS.CREATORUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setCreatoruserid(String creatoruserid) {
		this.creatoruserid = creatoruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.OWNERUSERID
	 * @return  the value of CRM_BUSINESS.OWNERUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getOwneruserid() {
		return owneruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.OWNERUSERID
	 * @param owneruserid  the value for CRM_BUSINESS.OWNERUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setOwneruserid(String owneruserid) {
		this.owneruserid = owneruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.GAINRATE
	 * @return  the value of CRM_BUSINESS.GAINRATE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public BigDecimal getGainrate() {
		return gainrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.GAINRATE
	 * @param gainrate  the value for CRM_BUSINESS.GAINRATE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setGainrate(BigDecimal gainrate) {
		this.gainrate = gainrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.TOTALAMOUNT
	 * @return  the value of CRM_BUSINESS.TOTALAMOUNT
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Long getTotalamount() {
		return totalamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.TOTALAMOUNT
	 * @param totalamount  the value for CRM_BUSINESS.TOTALAMOUNT
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setTotalamount(Long totalamount) {
		this.totalamount = totalamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.SUBTOTALVAL
	 * @return  the value of CRM_BUSINESS.SUBTOTALVAL
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public BigDecimal getSubtotalval() {
		return subtotalval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.SUBTOTALVAL
	 * @param subtotalval  the value for CRM_BUSINESS.SUBTOTALVAL
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setSubtotalval(BigDecimal subtotalval) {
		this.subtotalval = subtotalval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.DISCOUNTPRICE
	 * @return  the value of CRM_BUSINESS.DISCOUNTPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Long getDiscountprice() {
		return discountprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.DISCOUNTPRICE
	 * @param discountprice  the value for CRM_BUSINESS.DISCOUNTPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setDiscountprice(Long discountprice) {
		this.discountprice = discountprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.SALESPRICE
	 * @return  the value of CRM_BUSINESS.SALESPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Long getSalesprice() {
		return salesprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.SALESPRICE
	 * @param salesprice  the value for CRM_BUSINESS.SALESPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setSalesprice(Long salesprice) {
		this.salesprice = salesprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.DUEDATE
	 * @return  the value of CRM_BUSINESS.DUEDATE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Date getDuedate() {
		return duedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.DUEDATE
	 * @param duedate  the value for CRM_BUSINESS.DUEDATE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.GMT_CREATE
	 * @return  the value of CRM_BUSINESS.GMT_CREATE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.GMT_CREATE
	 * @param gmtCreate  the value for CRM_BUSINESS.GMT_CREATE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.GMT_MODIFIED
	 * @return  the value of CRM_BUSINESS.GMT_MODIFIED
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.GMT_MODIFIED
	 * @param gmtModified  the value for CRM_BUSINESS.GMT_MODIFIED
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.UPDATEUSERID
	 * @return  the value of CRM_BUSINESS.UPDATEUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getUpdateuserid() {
		return updateuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.UPDATEUSERID
	 * @param updateuserid  the value for CRM_BUSINESS.UPDATEUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setUpdateuserid(String updateuserid) {
		this.updateuserid = updateuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.STATUSID
	 * @return  the value of CRM_BUSINESS.STATUSID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getStatusid() {
		return statusid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.STATUSID
	 * @param statusid  the value for CRM_BUSINESS.STATUSID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setStatusid(String statusid) {
		this.statusid = statusid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.TOTALPRICE
	 * @return  the value of CRM_BUSINESS.TOTALPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Long getTotalprice() {
		return totalprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.TOTALPRICE
	 * @param totalprice  the value for CRM_BUSINESS.TOTALPRICE
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setTotalprice(Long totalprice) {
		this.totalprice = totalprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.NEXTSTEP
	 * @return  the value of CRM_BUSINESS.NEXTSTEP
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getNextstep() {
		return nextstep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.NEXTSTEP
	 * @param nextstep  the value for CRM_BUSINESS.NEXTSTEP
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setNextstep(String nextstep) {
		this.nextstep = nextstep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.NEXTSTEPTIME
	 * @return  the value of CRM_BUSINESS.NEXTSTEPTIME
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getNextsteptime() {
		return nextsteptime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.NEXTSTEPTIME
	 * @param nextsteptime  the value for CRM_BUSINESS.NEXTSTEPTIME
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setNextsteptime(String nextsteptime) {
		this.nextsteptime = nextsteptime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.ISDELETED
	 * @return  the value of CRM_BUSINESS.ISDELETED
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Long getIsdeleted() {
		return isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.ISDELETED
	 * @param isdeleted  the value for CRM_BUSINESS.ISDELETED
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setIsdeleted(Long isdeleted) {
		this.isdeleted = isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.DELETEUSERID
	 * @return  the value of CRM_BUSINESS.DELETEUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getDeleteuserid() {
		return deleteuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.DELETEUSERID
	 * @param deleteuserid  the value for CRM_BUSINESS.DELETEUSERID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setDeleteuserid(String deleteuserid) {
		this.deleteuserid = deleteuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.DELETETIME
	 * @return  the value of CRM_BUSINESS.DELETETIME
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Date getDeletetime() {
		return deletetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.DELETETIME
	 * @param deletetime  the value for CRM_BUSINESS.DELETETIME
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setDeletetime(Date deletetime) {
		this.deletetime = deletetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.CONTACTSID
	 * @return  the value of CRM_BUSINESS.CONTACTSID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public Long getContactsid() {
		return contactsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.CONTACTSID
	 * @param contactsid  the value for CRM_BUSINESS.CONTACTSID
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setContactsid(Long contactsid) {
		this.contactsid = contactsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.CONTACTADDRESS
	 * @return  the value of CRM_BUSINESS.CONTACTADDRESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getContactaddress() {
		return contactaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.CONTACTADDRESS
	 * @param contactaddress  the value for CRM_BUSINESS.CONTACTADDRESS
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setContactaddress(String contactaddress) {
		this.contactaddress = contactaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.DESCRIPTION
	 * @return  the value of CRM_BUSINESS.DESCRIPTION
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.DESCRIPTION
	 * @param description  the value for CRM_BUSINESS.DESCRIPTION
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRM_BUSINESS.IS_DEL
	 * @return  the value of CRM_BUSINESS.IS_DEL
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public String getIsDel() {
		return isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRM_BUSINESS.IS_DEL
	 * @param isDel  the value for CRM_BUSINESS.IS_DEL
	 * @mbg.generated  Thu Mar 15 09:59:41 CST 2018
	 */
	public void setIsDel(String isDel) {
		this.isDel = isDel;
	}
}